blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/necofuryai/todo/issues/new?template=custom.md&projects=necofuryai%2Ftodo%2F1&labels=ToDo