blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: Add new ToDo made by config.yml
    url: https://github.com/necofuryai/mytodo/issues/new?template=custom.md&projects=necofuryai%2Fmytodo%2F1&labels=ToDo